/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 can.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useLoader } from "@react-three/fiber";
import { TextureLoader, DoubleSide } from "three";
import { useCustomGLTF } from "../../hooks/useCustomGLTF";

export function SimpleCan(props) {
  const { scene } = useCustomGLTF('/can.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  // 텍스처 로드
  const texture = useLoader(TextureLoader, "/sample.png");


  return (
    <group>
      {/* 캔 윗면 (뚜껑) */}
      <mesh position={[0, 0.5, 0]}>
        <cylinderGeometry args={[0.5, 0.5, 0.05, 32]} />
        <meshStandardMaterial color="silver" />
      </mesh>

      {/* 캔 원통형 몸체 */}
      <mesh position={[0, 0, 0]}>
        <cylinderGeometry args={[0.5, 0.5, 1, 32, 1, true]} />
        <meshStandardMaterial map={texture} />
      </mesh>

      {/* 캔 아랫면 (바닥) */}
      <mesh position={[0, -0.5, 0]}>
        <cylinderGeometry args={[0.5, 0.5, 0.05, 32]} />
        <meshStandardMaterial color="silver" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/can.gltf')
