/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 PACK1000_WOOD.gltf 
*/

import React, { useEffect } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { TextureLoader, Color, SRGBColorSpace } from 'three'

export function PACK1000_WOOD({ imageSrc, color1, ...props }) {
  const { nodes, materials } = useGLTF('/PACK1000_WOOD.gltf')


  // 텍스처 로드 (예시로 '/path/to/texture.jpg' 경로를 사용)
  // const texture = useTexture(imageSrc)
  //texture.colorSpace = SRGBColorSpace // 일반적인 텍스처에는 이게 적절함

  // 특정 매터리얼에 텍스처 적용
  

  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.평면002.geometry} material={materials['매테리얼.002']} position={[-1.036, 3.642, -0.487]} rotation={[-1.56, -0.001, -1.636]} scale={[0.737, 0.537, 0.537]} />
      <mesh castShadow receiveShadow geometry={nodes.평면003.geometry} material={materials['매테리얼.002']} position={[0.679, 3.642, -0.376]} rotation={[-1.558, -0.001, 1.506]} scale={[-0.737, 0.537, 0.537]} />
      <mesh castShadow receiveShadow geometry={nodes.실린더001.geometry} material={materials.material} position={[-0.2, 4.369, -0.184]} rotation={[0, 1.506, 0.131]} scale={[0.396, 0.106, 0.396]} />
      <mesh castShadow receiveShadow geometry={nodes.큐브002.geometry} material={materials['매테리얼.004']} position={[-0.183, 2.399, -0.415]} rotation={[0, 1.506, 0]} scale={[0.819, 2.15, 0.819]} />
    </group>
  )
}

useGLTF.preload('/PACK1000_WOOD.gltf')

