/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 result.gltf 
*/

import React, { useEffect } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { TextureLoader, Color } from 'three'

export function PACK1000({ imageSrc, ...props }) {

  const { nodes, materials } = useGLTF('/result.gltf')

  // 텍스처 로드 (예시로 '/path/to/texture.jpg' 경로를 사용)
  const texture = useTexture(imageSrc)

  // 특정 매터리얼에 텍스처 적용
  useEffect(() => {

    if (imageSrc) {
      if (materials.Material) {
        materials.Material.map = texture
        materials.Material.needsUpdate = true // 텍스처 적용 후 업데이트 필요
      }
    }


    if (materials['매테리얼.001']) {
      materials['매테리얼.001'].color = new Color('#00A86B')
      materials['매테리얼.001'].needsUpdate = true
    }

    if (materials['materials.Material']) {
      materials['materials.Material'].color = new Color('#00A86B')
      materials['materials.Material'].needsUpdate = true
    }

  }, [materials, imageSrc, texture])

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.큐브001.geometry} material={materials.Material} position={[-0.022, 1.865, -0.007]} scale={[0.836, 2, 0.836]} />
      <mesh geometry={nodes.실린더003.geometry} material={materials.매테리얼} position={[-0.054, 3.814, 0.002]} rotation={[0, 0, 0.131]} scale={[0.396, 0.106, 0.396]} />
      <mesh geometry={nodes.평면.geometry} material={materials['매테리얼.001']} position={[-0.023, 3.063, 0.841]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.737, 0.537, 0.537]} />
      <mesh geometry={nodes.평면001.geometry} material={materials['매테리얼.001']} position={[-0.023, 3.063, -0.853]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.737, 0.537, 0.537]} />
    </group>
  )
}

useGLTF.preload('/result.gltf')
