/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: hishamhamid🦊 (https://sketchfab.com/hishamhaizz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fragile-boxes-aa8e9bcc2add4eadba138de4ceaba364
Title: Fragile Boxes
*/
import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { useCustomGLTF } from "../hooks/useCustomGLTF";
export function Model1(props) {

  const { nodes, materials } = useCustomGLTF('scene.gltf')


  useEffect(() => {
    const texture = materials.lambert4?.map  // 기존 텍스처 가져오기


    if (texture) {

      texture.image = null  // 기존 이미지를 null로 설정하여 초기화
      texture.image = new Image()  // 새로운 이미지 객체 생성
      texture.image.src = '/sample.png'  // 새로운 이미지 경로 지정

      // 텍스처 로드 후 다시 업데이트
      texture.needsUpdate = true
    }
  }, [materials])



  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCube2_lambert4_0.geometry} material={materials.lambert4} position={[2.019, 1.676, 1.874]} rotation={[0, -0.407, 0]} scale={3.299} />
      <mesh geometry={nodes.pCube3_lambert4_0.geometry} material={materials.lambert4} position={[5.127, 2.289, -3.603]} rotation={[0, 0.24, 0]} scale={4.614} />
      <mesh geometry={nodes.pCube6_lambert4_0.geometry} material={materials.lambert4} position={[-2.79, 1.676, -0.635]} rotation={[0, 0.429, 0]} scale={3.299} />
      <mesh geometry={nodes.pCube2_lambert4_0.geometry} material={materials.lambert4} position={[2.019, 1.676, 1.874]} rotation={[0, -0.407, 0]} scale={3.299} />

    </group>
  )
}

useGLTF.preload('/scene.gltf')
